# Generated by Django 6.1.1 on 2026-09-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='program',
        ),
    ]
